# Font Settings
font-family = "JetBrainsMono Nerd Font"
font-size = 14
font-thicken = true

# Cursor & Mouse
cursor-style = block
cursor-style-blink = false
mouse-hide-while-typing = true
mouse-scroll-multiplier = 2

# Window & Transparency
background-opacity = 0.95
background-blur-radius = 20
window-padding-x = 10
window-padding-y = 10
window-padding-balance = true
window-decoration = true
macos-titlebar-style = transparent

# Behavior & Theme
theme = Gruvbox Dark Hard
shell-integration = zsh
quit-after-last-window-closed = true

